package com.alibabasmt.database.smtaccount.mapper;

import com.alibabasmt.database.smtaccount.model.SmtUserAccount;
import com.alibabasmt.database.smtaccount.model.SmtUserAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    int countByExample(SmtUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    int deleteByExample(SmtUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    int insert(SmtUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    int insertSelective(SmtUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    List<SmtUserAccount> selectByExample(SmtUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    SmtUserAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtUserAccount record, @Param("example") SmtUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtUserAccount record, @Param("example") SmtUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtUserAccount record);
}