package com.alibabasmt.database.smtaccount.mapper;

import com.alibabasmt.database.smtaccount.model.SmtUserAccountManager;
import com.alibabasmt.database.smtaccount.model.SmtUserAccountManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtUserAccountManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    int countByExample(SmtUserAccountManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    int deleteByExample(SmtUserAccountManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    int insert(SmtUserAccountManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    int insertSelective(SmtUserAccountManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    List<SmtUserAccountManager> selectByExample(SmtUserAccountManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    SmtUserAccountManager selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtUserAccountManager record, @Param("example") SmtUserAccountManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtUserAccountManager record, @Param("example") SmtUserAccountManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtUserAccountManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_user_account_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtUserAccountManager record);
}