package com.alibabasmt.database.smtshipping.mapper;

import com.alibabasmt.database.smtshipping.model.SmtShippingTemplateDetail;
import com.alibabasmt.database.smtshipping.model.SmtShippingTemplateDetailExample;
import com.alibabasmt.database.smtshipping.model.SmtShippingTemplateDetailWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtShippingTemplateDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int countByExample(SmtShippingTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int deleteByExample(SmtShippingTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int insert(SmtShippingTemplateDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int insertSelective(SmtShippingTemplateDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    List<SmtShippingTemplateDetailWithBLOBs> selectByExampleWithBLOBs(SmtShippingTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    List<SmtShippingTemplateDetail> selectByExample(SmtShippingTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    SmtShippingTemplateDetailWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtShippingTemplateDetailWithBLOBs record, @Param("example") SmtShippingTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SmtShippingTemplateDetailWithBLOBs record, @Param("example") SmtShippingTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtShippingTemplateDetail record, @Param("example") SmtShippingTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtShippingTemplateDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SmtShippingTemplateDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtShippingTemplateDetail record);
}