package com.alibabasmt.database.smtshipping.mapper;

import com.alibabasmt.database.smtshipping.model.SmtShippingSelfstandard;
import com.alibabasmt.database.smtshipping.model.SmtShippingSelfstandardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtShippingSelfstandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int countByExample(SmtShippingSelfstandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int deleteByExample(SmtShippingSelfstandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int insert(SmtShippingSelfstandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int insertSelective(SmtShippingSelfstandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    List<SmtShippingSelfstandard> selectByExampleWithBLOBs(SmtShippingSelfstandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    List<SmtShippingSelfstandard> selectByExample(SmtShippingSelfstandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    SmtShippingSelfstandard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtShippingSelfstandard record, @Param("example") SmtShippingSelfstandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SmtShippingSelfstandard record, @Param("example") SmtShippingSelfstandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtShippingSelfstandard record, @Param("example") SmtShippingSelfstandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtShippingSelfstandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SmtShippingSelfstandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_selfstandard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtShippingSelfstandard record);
}