package com.alibabasmt.database.smtshipping.mapper;

import com.alibabasmt.database.smtshipping.model.SmtShippingTemplate;
import com.alibabasmt.database.smtshipping.model.SmtShippingTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtShippingTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    int countByExample(SmtShippingTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    int deleteByExample(SmtShippingTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    int insert(SmtShippingTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    int insertSelective(SmtShippingTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    List<SmtShippingTemplate> selectByExample(SmtShippingTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    SmtShippingTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtShippingTemplate record, @Param("example") SmtShippingTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtShippingTemplate record, @Param("example") SmtShippingTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtShippingTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_shipping_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtShippingTemplate record);
}