package com.base.database.userinfo.mapper;

import com.base.database.userinfo.model.SystemInvitationCode;
import com.base.database.userinfo.model.SystemInvitationCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemInvitationCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    int countByExample(SystemInvitationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    int deleteByExample(SystemInvitationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    int insert(SystemInvitationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    int insertSelective(SystemInvitationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    List<SystemInvitationCode> selectByExample(SystemInvitationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    SystemInvitationCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemInvitationCode record, @Param("example") SystemInvitationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemInvitationCode record, @Param("example") SystemInvitationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemInvitationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_invitation_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemInvitationCode record);
}