package com.base.database.userinfo.mapper;

import com.base.database.userinfo.model.UsercontrollerUserThirdMark;
import com.base.database.userinfo.model.UsercontrollerUserThirdMarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsercontrollerUserThirdMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    int countByExample(UsercontrollerUserThirdMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    int deleteByExample(UsercontrollerUserThirdMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    int insert(UsercontrollerUserThirdMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    int insertSelective(UsercontrollerUserThirdMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    List<UsercontrollerUserThirdMark> selectByExample(UsercontrollerUserThirdMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    UsercontrollerUserThirdMark selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsercontrollerUserThirdMark record, @Param("example") UsercontrollerUserThirdMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsercontrollerUserThirdMark record, @Param("example") UsercontrollerUserThirdMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsercontrollerUserThirdMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_third_mark
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsercontrollerUserThirdMark record);
}