package com.base.database.userinfo.mapper;

import com.base.database.userinfo.model.UsercontrollerUserBill;
import com.base.database.userinfo.model.UsercontrollerUserBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsercontrollerUserBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    int countByExample(UsercontrollerUserBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    int deleteByExample(UsercontrollerUserBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    int insert(UsercontrollerUserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    int insertSelective(UsercontrollerUserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    List<UsercontrollerUserBill> selectByExample(UsercontrollerUserBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    UsercontrollerUserBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsercontrollerUserBill record, @Param("example") UsercontrollerUserBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsercontrollerUserBill record, @Param("example") UsercontrollerUserBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsercontrollerUserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsercontrollerUserBill record);
}