package com.base.database.userinfo.mapper;

import com.base.database.userinfo.model.UsercontrollerVipUser;
import com.base.database.userinfo.model.UsercontrollerVipUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsercontrollerVipUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    int countByExample(UsercontrollerVipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    int deleteByExample(UsercontrollerVipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    int insert(UsercontrollerVipUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    int insertSelective(UsercontrollerVipUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    List<UsercontrollerVipUser> selectByExample(UsercontrollerVipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    UsercontrollerVipUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsercontrollerVipUser record, @Param("example") UsercontrollerVipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsercontrollerVipUser record, @Param("example") UsercontrollerVipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsercontrollerVipUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_vip_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsercontrollerVipUser record);
}