package com.base.database.userinfo.mapper;

import com.base.database.userinfo.model.UsercontrollerThirdPart;
import com.base.database.userinfo.model.UsercontrollerThirdPartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsercontrollerThirdPartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    int countByExample(UsercontrollerThirdPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    int deleteByExample(UsercontrollerThirdPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    int insert(UsercontrollerThirdPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    int insertSelective(UsercontrollerThirdPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    List<UsercontrollerThirdPart> selectByExample(UsercontrollerThirdPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    UsercontrollerThirdPart selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsercontrollerThirdPart record, @Param("example") UsercontrollerThirdPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsercontrollerThirdPart record, @Param("example") UsercontrollerThirdPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsercontrollerThirdPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_third_part
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsercontrollerThirdPart record);
}