package com.alibabasmt.database.smtorder.model;

import java.util.Date;

public class SmtOrderProductAttributes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.productId
     *
     * @mbggenerated
     */
    private Long productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.orderd
     *
     * @mbggenerated
     */
    private Integer orderd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.pId
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.pName
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.pValue
     *
     * @mbggenerated
     */
    private String pvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.pValueId
     *
     * @mbggenerated
     */
    private String pvalueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.selfDefineValue
     *
     * @mbggenerated
     */
    private String selfdefinevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.showType
     *
     * @mbggenerated
     */
    private String showtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.skuImg
     *
     * @mbggenerated
     */
    private String skuimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_order_product_attributes.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.id
     *
     * @return the value of smt_order_product_attributes.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.id
     *
     * @param id the value for smt_order_product_attributes.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.productId
     *
     * @return the value of smt_order_product_attributes.productId
     *
     * @mbggenerated
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.productId
     *
     * @param productid the value for smt_order_product_attributes.productId
     *
     * @mbggenerated
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.orderd
     *
     * @return the value of smt_order_product_attributes.orderd
     *
     * @mbggenerated
     */
    public Integer getOrderd() {
        return orderd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.orderd
     *
     * @param orderd the value for smt_order_product_attributes.orderd
     *
     * @mbggenerated
     */
    public void setOrderd(Integer orderd) {
        this.orderd = orderd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.pId
     *
     * @return the value of smt_order_product_attributes.pId
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.pId
     *
     * @param pid the value for smt_order_product_attributes.pId
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.pName
     *
     * @return the value of smt_order_product_attributes.pName
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.pName
     *
     * @param pname the value for smt_order_product_attributes.pName
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.pValue
     *
     * @return the value of smt_order_product_attributes.pValue
     *
     * @mbggenerated
     */
    public String getPvalue() {
        return pvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.pValue
     *
     * @param pvalue the value for smt_order_product_attributes.pValue
     *
     * @mbggenerated
     */
    public void setPvalue(String pvalue) {
        this.pvalue = pvalue == null ? null : pvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.pValueId
     *
     * @return the value of smt_order_product_attributes.pValueId
     *
     * @mbggenerated
     */
    public String getPvalueid() {
        return pvalueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.pValueId
     *
     * @param pvalueid the value for smt_order_product_attributes.pValueId
     *
     * @mbggenerated
     */
    public void setPvalueid(String pvalueid) {
        this.pvalueid = pvalueid == null ? null : pvalueid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.selfDefineValue
     *
     * @return the value of smt_order_product_attributes.selfDefineValue
     *
     * @mbggenerated
     */
    public String getSelfdefinevalue() {
        return selfdefinevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.selfDefineValue
     *
     * @param selfdefinevalue the value for smt_order_product_attributes.selfDefineValue
     *
     * @mbggenerated
     */
    public void setSelfdefinevalue(String selfdefinevalue) {
        this.selfdefinevalue = selfdefinevalue == null ? null : selfdefinevalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.showType
     *
     * @return the value of smt_order_product_attributes.showType
     *
     * @mbggenerated
     */
    public String getShowtype() {
        return showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.showType
     *
     * @param showtype the value for smt_order_product_attributes.showType
     *
     * @mbggenerated
     */
    public void setShowtype(String showtype) {
        this.showtype = showtype == null ? null : showtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.skuImg
     *
     * @return the value of smt_order_product_attributes.skuImg
     *
     * @mbggenerated
     */
    public String getSkuimg() {
        return skuimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.skuImg
     *
     * @param skuimg the value for smt_order_product_attributes.skuImg
     *
     * @mbggenerated
     */
    public void setSkuimg(String skuimg) {
        this.skuimg = skuimg == null ? null : skuimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.create_user
     *
     * @return the value of smt_order_product_attributes.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.create_user
     *
     * @param createUser the value for smt_order_product_attributes.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.create_time
     *
     * @return the value of smt_order_product_attributes.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.create_time
     *
     * @param createTime the value for smt_order_product_attributes.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_order_product_attributes.update_time
     *
     * @return the value of smt_order_product_attributes.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_order_product_attributes.update_time
     *
     * @param updateTime the value for smt_order_product_attributes.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}