package com.alibabasmt.database.smtorder.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SmtOrderChildOrderDetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public SmtOrderChildOrderDetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChildidIsNull() {
            addCriterion("childId is null");
            return (Criteria) this;
        }

        public Criteria andChildidIsNotNull() {
            addCriterion("childId is not null");
            return (Criteria) this;
        }

        public Criteria andChildidEqualTo(String value) {
            addCriterion("childId =", value, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidNotEqualTo(String value) {
            addCriterion("childId <>", value, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidGreaterThan(String value) {
            addCriterion("childId >", value, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidGreaterThanOrEqualTo(String value) {
            addCriterion("childId >=", value, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidLessThan(String value) {
            addCriterion("childId <", value, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidLessThanOrEqualTo(String value) {
            addCriterion("childId <=", value, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidLike(String value) {
            addCriterion("childId like", value, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidNotLike(String value) {
            addCriterion("childId not like", value, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidIn(List<String> values) {
            addCriterion("childId in", values, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidNotIn(List<String> values) {
            addCriterion("childId not in", values, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidBetween(String value1, String value2) {
            addCriterion("childId between", value1, value2, "childid");
            return (Criteria) this;
        }

        public Criteria andChildidNotBetween(String value1, String value2) {
            addCriterion("childId not between", value1, value2, "childid");
            return (Criteria) this;
        }

        public Criteria andProductidIsNull() {
            addCriterion("productId is null");
            return (Criteria) this;
        }

        public Criteria andProductidIsNotNull() {
            addCriterion("productId is not null");
            return (Criteria) this;
        }

        public Criteria andProductidEqualTo(Long value) {
            addCriterion("productId =", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotEqualTo(Long value) {
            addCriterion("productId <>", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThan(Long value) {
            addCriterion("productId >", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThanOrEqualTo(Long value) {
            addCriterion("productId >=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThan(Long value) {
            addCriterion("productId <", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThanOrEqualTo(Long value) {
            addCriterion("productId <=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidIn(List<Long> values) {
            addCriterion("productId in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotIn(List<Long> values) {
            addCriterion("productId not in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidBetween(Long value1, Long value2) {
            addCriterion("productId between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotBetween(Long value1, Long value2) {
            addCriterion("productId not between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andFundstatusIsNull() {
            addCriterion("fundStatus is null");
            return (Criteria) this;
        }

        public Criteria andFundstatusIsNotNull() {
            addCriterion("fundStatus is not null");
            return (Criteria) this;
        }

        public Criteria andFundstatusEqualTo(String value) {
            addCriterion("fundStatus =", value, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusNotEqualTo(String value) {
            addCriterion("fundStatus <>", value, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusGreaterThan(String value) {
            addCriterion("fundStatus >", value, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusGreaterThanOrEqualTo(String value) {
            addCriterion("fundStatus >=", value, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusLessThan(String value) {
            addCriterion("fundStatus <", value, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusLessThanOrEqualTo(String value) {
            addCriterion("fundStatus <=", value, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusLike(String value) {
            addCriterion("fundStatus like", value, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusNotLike(String value) {
            addCriterion("fundStatus not like", value, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusIn(List<String> values) {
            addCriterion("fundStatus in", values, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusNotIn(List<String> values) {
            addCriterion("fundStatus not in", values, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusBetween(String value1, String value2) {
            addCriterion("fundStatus between", value1, value2, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andFundstatusNotBetween(String value1, String value2) {
            addCriterion("fundStatus not between", value1, value2, "fundstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIsNull() {
            addCriterion("orderStatus is null");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIsNotNull() {
            addCriterion("orderStatus is not null");
            return (Criteria) this;
        }

        public Criteria andOrderstatusEqualTo(String value) {
            addCriterion("orderStatus =", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotEqualTo(String value) {
            addCriterion("orderStatus <>", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusGreaterThan(String value) {
            addCriterion("orderStatus >", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusGreaterThanOrEqualTo(String value) {
            addCriterion("orderStatus >=", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLessThan(String value) {
            addCriterion("orderStatus <", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLessThanOrEqualTo(String value) {
            addCriterion("orderStatus <=", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLike(String value) {
            addCriterion("orderStatus like", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotLike(String value) {
            addCriterion("orderStatus not like", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIn(List<String> values) {
            addCriterion("orderStatus in", values, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotIn(List<String> values) {
            addCriterion("orderStatus not in", values, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusBetween(String value1, String value2) {
            addCriterion("orderStatus between", value1, value2, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotBetween(String value1, String value2) {
            addCriterion("orderStatus not between", value1, value2, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andInitorderamtIsNull() {
            addCriterion("initOrderAmt is null");
            return (Criteria) this;
        }

        public Criteria andInitorderamtIsNotNull() {
            addCriterion("initOrderAmt is not null");
            return (Criteria) this;
        }

        public Criteria andInitorderamtEqualTo(String value) {
            addCriterion("initOrderAmt =", value, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtNotEqualTo(String value) {
            addCriterion("initOrderAmt <>", value, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtGreaterThan(String value) {
            addCriterion("initOrderAmt >", value, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtGreaterThanOrEqualTo(String value) {
            addCriterion("initOrderAmt >=", value, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtLessThan(String value) {
            addCriterion("initOrderAmt <", value, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtLessThanOrEqualTo(String value) {
            addCriterion("initOrderAmt <=", value, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtLike(String value) {
            addCriterion("initOrderAmt like", value, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtNotLike(String value) {
            addCriterion("initOrderAmt not like", value, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtIn(List<String> values) {
            addCriterion("initOrderAmt in", values, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtNotIn(List<String> values) {
            addCriterion("initOrderAmt not in", values, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtBetween(String value1, String value2) {
            addCriterion("initOrderAmt between", value1, value2, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtNotBetween(String value1, String value2) {
            addCriterion("initOrderAmt not between", value1, value2, "initorderamt");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyIsNull() {
            addCriterion("initOrderAmtCurrency is null");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyIsNotNull() {
            addCriterion("initOrderAmtCurrency is not null");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyEqualTo(String value) {
            addCriterion("initOrderAmtCurrency =", value, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyNotEqualTo(String value) {
            addCriterion("initOrderAmtCurrency <>", value, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyGreaterThan(String value) {
            addCriterion("initOrderAmtCurrency >", value, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("initOrderAmtCurrency >=", value, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyLessThan(String value) {
            addCriterion("initOrderAmtCurrency <", value, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyLessThanOrEqualTo(String value) {
            addCriterion("initOrderAmtCurrency <=", value, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyLike(String value) {
            addCriterion("initOrderAmtCurrency like", value, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyNotLike(String value) {
            addCriterion("initOrderAmtCurrency not like", value, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyIn(List<String> values) {
            addCriterion("initOrderAmtCurrency in", values, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyNotIn(List<String> values) {
            addCriterion("initOrderAmtCurrency not in", values, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyBetween(String value1, String value2) {
            addCriterion("initOrderAmtCurrency between", value1, value2, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andInitorderamtcurrencyNotBetween(String value1, String value2) {
            addCriterion("initOrderAmtCurrency not between", value1, value2, "initorderamtcurrency");
            return (Criteria) this;
        }

        public Criteria andProductunitIsNull() {
            addCriterion("productUnit is null");
            return (Criteria) this;
        }

        public Criteria andProductunitIsNotNull() {
            addCriterion("productUnit is not null");
            return (Criteria) this;
        }

        public Criteria andProductunitEqualTo(String value) {
            addCriterion("productUnit =", value, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitNotEqualTo(String value) {
            addCriterion("productUnit <>", value, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitGreaterThan(String value) {
            addCriterion("productUnit >", value, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitGreaterThanOrEqualTo(String value) {
            addCriterion("productUnit >=", value, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitLessThan(String value) {
            addCriterion("productUnit <", value, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitLessThanOrEqualTo(String value) {
            addCriterion("productUnit <=", value, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitLike(String value) {
            addCriterion("productUnit like", value, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitNotLike(String value) {
            addCriterion("productUnit not like", value, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitIn(List<String> values) {
            addCriterion("productUnit in", values, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitNotIn(List<String> values) {
            addCriterion("productUnit not in", values, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitBetween(String value1, String value2) {
            addCriterion("productUnit between", value1, value2, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductunitNotBetween(String value1, String value2) {
            addCriterion("productUnit not between", value1, value2, "productunit");
            return (Criteria) this;
        }

        public Criteria andProductcountIsNull() {
            addCriterion("productCount is null");
            return (Criteria) this;
        }

        public Criteria andProductcountIsNotNull() {
            addCriterion("productCount is not null");
            return (Criteria) this;
        }

        public Criteria andProductcountEqualTo(Integer value) {
            addCriterion("productCount =", value, "productcount");
            return (Criteria) this;
        }

        public Criteria andProductcountNotEqualTo(Integer value) {
            addCriterion("productCount <>", value, "productcount");
            return (Criteria) this;
        }

        public Criteria andProductcountGreaterThan(Integer value) {
            addCriterion("productCount >", value, "productcount");
            return (Criteria) this;
        }

        public Criteria andProductcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("productCount >=", value, "productcount");
            return (Criteria) this;
        }

        public Criteria andProductcountLessThan(Integer value) {
            addCriterion("productCount <", value, "productcount");
            return (Criteria) this;
        }

        public Criteria andProductcountLessThanOrEqualTo(Integer value) {
            addCriterion("productCount <=", value, "productcount");
            return (Criteria) this;
        }

        public Criteria andProductcountIn(List<Integer> values) {
            addCriterion("productCount in", values, "productcount");
            return (Criteria) this;
        }

        public Criteria andProductcountNotIn(List<Integer> values) {
            addCriterion("productCount not in", values, "productcount");
            return (Criteria) this;
        }

        public Criteria andProductcountBetween(Integer value1, Integer value2) {
            addCriterion("productCount between", value1, value2, "productcount");
            return (Criteria) this;
        }

        public Criteria andProductcountNotBetween(Integer value1, Integer value2) {
            addCriterion("productCount not between", value1, value2, "productcount");
            return (Criteria) this;
        }

        public Criteria andLotnumIsNull() {
            addCriterion("lotNum is null");
            return (Criteria) this;
        }

        public Criteria andLotnumIsNotNull() {
            addCriterion("lotNum is not null");
            return (Criteria) this;
        }

        public Criteria andLotnumEqualTo(Integer value) {
            addCriterion("lotNum =", value, "lotnum");
            return (Criteria) this;
        }

        public Criteria andLotnumNotEqualTo(Integer value) {
            addCriterion("lotNum <>", value, "lotnum");
            return (Criteria) this;
        }

        public Criteria andLotnumGreaterThan(Integer value) {
            addCriterion("lotNum >", value, "lotnum");
            return (Criteria) this;
        }

        public Criteria andLotnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("lotNum >=", value, "lotnum");
            return (Criteria) this;
        }

        public Criteria andLotnumLessThan(Integer value) {
            addCriterion("lotNum <", value, "lotnum");
            return (Criteria) this;
        }

        public Criteria andLotnumLessThanOrEqualTo(Integer value) {
            addCriterion("lotNum <=", value, "lotnum");
            return (Criteria) this;
        }

        public Criteria andLotnumIn(List<Integer> values) {
            addCriterion("lotNum in", values, "lotnum");
            return (Criteria) this;
        }

        public Criteria andLotnumNotIn(List<Integer> values) {
            addCriterion("lotNum not in", values, "lotnum");
            return (Criteria) this;
        }

        public Criteria andLotnumBetween(Integer value1, Integer value2) {
            addCriterion("lotNum between", value1, value2, "lotnum");
            return (Criteria) this;
        }

        public Criteria andLotnumNotBetween(Integer value1, Integer value2) {
            addCriterion("lotNum not between", value1, value2, "lotnum");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusIsNull() {
            addCriterion("frozenStatus is null");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusIsNotNull() {
            addCriterion("frozenStatus is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusEqualTo(String value) {
            addCriterion("frozenStatus =", value, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusNotEqualTo(String value) {
            addCriterion("frozenStatus <>", value, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusGreaterThan(String value) {
            addCriterion("frozenStatus >", value, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusGreaterThanOrEqualTo(String value) {
            addCriterion("frozenStatus >=", value, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusLessThan(String value) {
            addCriterion("frozenStatus <", value, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusLessThanOrEqualTo(String value) {
            addCriterion("frozenStatus <=", value, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusLike(String value) {
            addCriterion("frozenStatus like", value, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusNotLike(String value) {
            addCriterion("frozenStatus not like", value, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusIn(List<String> values) {
            addCriterion("frozenStatus in", values, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusNotIn(List<String> values) {
            addCriterion("frozenStatus not in", values, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusBetween(String value1, String value2) {
            addCriterion("frozenStatus between", value1, value2, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andFrozenstatusNotBetween(String value1, String value2) {
            addCriterion("frozenStatus not between", value1, value2, "frozenstatus");
            return (Criteria) this;
        }

        public Criteria andSkucodeIsNull() {
            addCriterion("skuCode is null");
            return (Criteria) this;
        }

        public Criteria andSkucodeIsNotNull() {
            addCriterion("skuCode is not null");
            return (Criteria) this;
        }

        public Criteria andSkucodeEqualTo(String value) {
            addCriterion("skuCode =", value, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeNotEqualTo(String value) {
            addCriterion("skuCode <>", value, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeGreaterThan(String value) {
            addCriterion("skuCode >", value, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeGreaterThanOrEqualTo(String value) {
            addCriterion("skuCode >=", value, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeLessThan(String value) {
            addCriterion("skuCode <", value, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeLessThanOrEqualTo(String value) {
            addCriterion("skuCode <=", value, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeLike(String value) {
            addCriterion("skuCode like", value, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeNotLike(String value) {
            addCriterion("skuCode not like", value, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeIn(List<String> values) {
            addCriterion("skuCode in", values, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeNotIn(List<String> values) {
            addCriterion("skuCode not in", values, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeBetween(String value1, String value2) {
            addCriterion("skuCode between", value1, value2, "skucode");
            return (Criteria) this;
        }

        public Criteria andSkucodeNotBetween(String value1, String value2) {
            addCriterion("skuCode not between", value1, value2, "skucode");
            return (Criteria) this;
        }

        public Criteria andIssuestatusIsNull() {
            addCriterion("issueStatus is null");
            return (Criteria) this;
        }

        public Criteria andIssuestatusIsNotNull() {
            addCriterion("issueStatus is not null");
            return (Criteria) this;
        }

        public Criteria andIssuestatusEqualTo(String value) {
            addCriterion("issueStatus =", value, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusNotEqualTo(String value) {
            addCriterion("issueStatus <>", value, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusGreaterThan(String value) {
            addCriterion("issueStatus >", value, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusGreaterThanOrEqualTo(String value) {
            addCriterion("issueStatus >=", value, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusLessThan(String value) {
            addCriterion("issueStatus <", value, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusLessThanOrEqualTo(String value) {
            addCriterion("issueStatus <=", value, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusLike(String value) {
            addCriterion("issueStatus like", value, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusNotLike(String value) {
            addCriterion("issueStatus not like", value, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusIn(List<String> values) {
            addCriterion("issueStatus in", values, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusNotIn(List<String> values) {
            addCriterion("issueStatus not in", values, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusBetween(String value1, String value2) {
            addCriterion("issueStatus between", value1, value2, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andIssuestatusNotBetween(String value1, String value2) {
            addCriterion("issueStatus not between", value1, value2, "issuestatus");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNull() {
            addCriterion("productName is null");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNotNull() {
            addCriterion("productName is not null");
            return (Criteria) this;
        }

        public Criteria andProductnameEqualTo(String value) {
            addCriterion("productName =", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotEqualTo(String value) {
            addCriterion("productName <>", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThan(String value) {
            addCriterion("productName >", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThanOrEqualTo(String value) {
            addCriterion("productName >=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThan(String value) {
            addCriterion("productName <", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThanOrEqualTo(String value) {
            addCriterion("productName <=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLike(String value) {
            addCriterion("productName like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotLike(String value) {
            addCriterion("productName not like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameIn(List<String> values) {
            addCriterion("productName in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotIn(List<String> values) {
            addCriterion("productName not in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameBetween(String value1, String value2) {
            addCriterion("productName between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotBetween(String value1, String value2) {
            addCriterion("productName not between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andProductpriceIsNull() {
            addCriterion("productPrice is null");
            return (Criteria) this;
        }

        public Criteria andProductpriceIsNotNull() {
            addCriterion("productPrice is not null");
            return (Criteria) this;
        }

        public Criteria andProductpriceEqualTo(String value) {
            addCriterion("productPrice =", value, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceNotEqualTo(String value) {
            addCriterion("productPrice <>", value, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceGreaterThan(String value) {
            addCriterion("productPrice >", value, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceGreaterThanOrEqualTo(String value) {
            addCriterion("productPrice >=", value, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceLessThan(String value) {
            addCriterion("productPrice <", value, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceLessThanOrEqualTo(String value) {
            addCriterion("productPrice <=", value, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceLike(String value) {
            addCriterion("productPrice like", value, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceNotLike(String value) {
            addCriterion("productPrice not like", value, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceIn(List<String> values) {
            addCriterion("productPrice in", values, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceNotIn(List<String> values) {
            addCriterion("productPrice not in", values, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceBetween(String value1, String value2) {
            addCriterion("productPrice between", value1, value2, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpriceNotBetween(String value1, String value2) {
            addCriterion("productPrice not between", value1, value2, "productprice");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyIsNull() {
            addCriterion("productPriceCurrency is null");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyIsNotNull() {
            addCriterion("productPriceCurrency is not null");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyEqualTo(String value) {
            addCriterion("productPriceCurrency =", value, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyNotEqualTo(String value) {
            addCriterion("productPriceCurrency <>", value, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyGreaterThan(String value) {
            addCriterion("productPriceCurrency >", value, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("productPriceCurrency >=", value, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyLessThan(String value) {
            addCriterion("productPriceCurrency <", value, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyLessThanOrEqualTo(String value) {
            addCriterion("productPriceCurrency <=", value, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyLike(String value) {
            addCriterion("productPriceCurrency like", value, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyNotLike(String value) {
            addCriterion("productPriceCurrency not like", value, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyIn(List<String> values) {
            addCriterion("productPriceCurrency in", values, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyNotIn(List<String> values) {
            addCriterion("productPriceCurrency not in", values, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyBetween(String value1, String value2) {
            addCriterion("productPriceCurrency between", value1, value2, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andProductpricecurrencyNotBetween(String value1, String value2) {
            addCriterion("productPriceCurrency not between", value1, value2, "productpricecurrency");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Long value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Long value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Long value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Long value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Long value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Long value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Long> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Long> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Long value1, Long value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Long value1, Long value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}