package com.alibabasmt.database.smttask.model;

import java.util.Date;

public class TaskSmtOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_smt_order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_smt_order.userid
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_smt_order.smt_amount_id
     *
     * @mbggenerated
     */
    private Long smtAmountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_smt_order.fromtime
     *
     * @mbggenerated
     */
    private String fromtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_smt_order.totime
     *
     * @mbggenerated
     */
    private String totime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_smt_order.tokenFlag
     *
     * @mbggenerated
     */
    private Integer tokenflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_smt_order.newUserFlag
     *
     * @mbggenerated
     */
    private Integer newuserflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_smt_order.savetime
     *
     * @mbggenerated
     */
    private Date savetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_smt_order.lastsyctime
     *
     * @mbggenerated
     */
    private Date lastsyctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_smt_order.id
     *
     * @return the value of task_smt_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_smt_order.id
     *
     * @param id the value for task_smt_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_smt_order.userid
     *
     * @return the value of task_smt_order.userid
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_smt_order.userid
     *
     * @param userid the value for task_smt_order.userid
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_smt_order.smt_amount_id
     *
     * @return the value of task_smt_order.smt_amount_id
     *
     * @mbggenerated
     */
    public Long getSmtAmountId() {
        return smtAmountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_smt_order.smt_amount_id
     *
     * @param smtAmountId the value for task_smt_order.smt_amount_id
     *
     * @mbggenerated
     */
    public void setSmtAmountId(Long smtAmountId) {
        this.smtAmountId = smtAmountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_smt_order.fromtime
     *
     * @return the value of task_smt_order.fromtime
     *
     * @mbggenerated
     */
    public String getFromtime() {
        return fromtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_smt_order.fromtime
     *
     * @param fromtime the value for task_smt_order.fromtime
     *
     * @mbggenerated
     */
    public void setFromtime(String fromtime) {
        this.fromtime = fromtime == null ? null : fromtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_smt_order.totime
     *
     * @return the value of task_smt_order.totime
     *
     * @mbggenerated
     */
    public String getTotime() {
        return totime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_smt_order.totime
     *
     * @param totime the value for task_smt_order.totime
     *
     * @mbggenerated
     */
    public void setTotime(String totime) {
        this.totime = totime == null ? null : totime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_smt_order.tokenFlag
     *
     * @return the value of task_smt_order.tokenFlag
     *
     * @mbggenerated
     */
    public Integer getTokenflag() {
        return tokenflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_smt_order.tokenFlag
     *
     * @param tokenflag the value for task_smt_order.tokenFlag
     *
     * @mbggenerated
     */
    public void setTokenflag(Integer tokenflag) {
        this.tokenflag = tokenflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_smt_order.newUserFlag
     *
     * @return the value of task_smt_order.newUserFlag
     *
     * @mbggenerated
     */
    public Integer getNewuserflag() {
        return newuserflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_smt_order.newUserFlag
     *
     * @param newuserflag the value for task_smt_order.newUserFlag
     *
     * @mbggenerated
     */
    public void setNewuserflag(Integer newuserflag) {
        this.newuserflag = newuserflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_smt_order.savetime
     *
     * @return the value of task_smt_order.savetime
     *
     * @mbggenerated
     */
    public Date getSavetime() {
        return savetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_smt_order.savetime
     *
     * @param savetime the value for task_smt_order.savetime
     *
     * @mbggenerated
     */
    public void setSavetime(Date savetime) {
        this.savetime = savetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_smt_order.lastsyctime
     *
     * @return the value of task_smt_order.lastsyctime
     *
     * @mbggenerated
     */
    public Date getLastsyctime() {
        return lastsyctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_smt_order.lastsyctime
     *
     * @param lastsyctime the value for task_smt_order.lastsyctime
     *
     * @mbggenerated
     */
    public void setLastsyctime(Date lastsyctime) {
        this.lastsyctime = lastsyctime;
    }
}