package com.base.database.userinfo.model;

import java.util.Date;

public class SystemInvitationCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_invitation_code.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_invitation_code.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_invitation_code.staut
     *
     * @mbggenerated
     */
    private String staut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_invitation_code.c_date
     *
     * @mbggenerated
     */
    private Date cDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_invitation_code.id
     *
     * @return the value of system_invitation_code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_invitation_code.id
     *
     * @param id the value for system_invitation_code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_invitation_code.code
     *
     * @return the value of system_invitation_code.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_invitation_code.code
     *
     * @param code the value for system_invitation_code.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_invitation_code.staut
     *
     * @return the value of system_invitation_code.staut
     *
     * @mbggenerated
     */
    public String getStaut() {
        return staut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_invitation_code.staut
     *
     * @param staut the value for system_invitation_code.staut
     *
     * @mbggenerated
     */
    public void setStaut(String staut) {
        this.staut = staut == null ? null : staut.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_invitation_code.c_date
     *
     * @return the value of system_invitation_code.c_date
     *
     * @mbggenerated
     */
    public Date getcDate() {
        return cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_invitation_code.c_date
     *
     * @param cDate the value for system_invitation_code.c_date
     *
     * @mbggenerated
     */
    public void setcDate(Date cDate) {
        this.cDate = cDate;
    }
}