package com.base.database.userinfo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsercontrollerUserBillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public UsercontrollerUserBillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBillSouceIsNull() {
            addCriterion("bill_souce is null");
            return (Criteria) this;
        }

        public Criteria andBillSouceIsNotNull() {
            addCriterion("bill_souce is not null");
            return (Criteria) this;
        }

        public Criteria andBillSouceEqualTo(String value) {
            addCriterion("bill_souce =", value, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceNotEqualTo(String value) {
            addCriterion("bill_souce <>", value, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceGreaterThan(String value) {
            addCriterion("bill_souce >", value, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceGreaterThanOrEqualTo(String value) {
            addCriterion("bill_souce >=", value, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceLessThan(String value) {
            addCriterion("bill_souce <", value, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceLessThanOrEqualTo(String value) {
            addCriterion("bill_souce <=", value, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceLike(String value) {
            addCriterion("bill_souce like", value, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceNotLike(String value) {
            addCriterion("bill_souce not like", value, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceIn(List<String> values) {
            addCriterion("bill_souce in", values, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceNotIn(List<String> values) {
            addCriterion("bill_souce not in", values, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceBetween(String value1, String value2) {
            addCriterion("bill_souce between", value1, value2, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSouceNotBetween(String value1, String value2) {
            addCriterion("bill_souce not between", value1, value2, "billSouce");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdIsNull() {
            addCriterion("bill_source_id is null");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdIsNotNull() {
            addCriterion("bill_source_id is not null");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdEqualTo(Integer value) {
            addCriterion("bill_source_id =", value, "billSourceId");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdNotEqualTo(Integer value) {
            addCriterion("bill_source_id <>", value, "billSourceId");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdGreaterThan(Integer value) {
            addCriterion("bill_source_id >", value, "billSourceId");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bill_source_id >=", value, "billSourceId");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdLessThan(Integer value) {
            addCriterion("bill_source_id <", value, "billSourceId");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdLessThanOrEqualTo(Integer value) {
            addCriterion("bill_source_id <=", value, "billSourceId");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdIn(List<Integer> values) {
            addCriterion("bill_source_id in", values, "billSourceId");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdNotIn(List<Integer> values) {
            addCriterion("bill_source_id not in", values, "billSourceId");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdBetween(Integer value1, Integer value2) {
            addCriterion("bill_source_id between", value1, value2, "billSourceId");
            return (Criteria) this;
        }

        public Criteria andBillSourceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bill_source_id not between", value1, value2, "billSourceId");
            return (Criteria) this;
        }

        public Criteria andBillTypeIsNull() {
            addCriterion("bill_type is null");
            return (Criteria) this;
        }

        public Criteria andBillTypeIsNotNull() {
            addCriterion("bill_type is not null");
            return (Criteria) this;
        }

        public Criteria andBillTypeEqualTo(String value) {
            addCriterion("bill_type =", value, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeNotEqualTo(String value) {
            addCriterion("bill_type <>", value, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeGreaterThan(String value) {
            addCriterion("bill_type >", value, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeGreaterThanOrEqualTo(String value) {
            addCriterion("bill_type >=", value, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeLessThan(String value) {
            addCriterion("bill_type <", value, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeLessThanOrEqualTo(String value) {
            addCriterion("bill_type <=", value, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeLike(String value) {
            addCriterion("bill_type like", value, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeNotLike(String value) {
            addCriterion("bill_type not like", value, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeIn(List<String> values) {
            addCriterion("bill_type in", values, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeNotIn(List<String> values) {
            addCriterion("bill_type not in", values, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeBetween(String value1, String value2) {
            addCriterion("bill_type between", value1, value2, "billType");
            return (Criteria) this;
        }

        public Criteria andBillTypeNotBetween(String value1, String value2) {
            addCriterion("bill_type not between", value1, value2, "billType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeIsNull() {
            addCriterion("costs_type is null");
            return (Criteria) this;
        }

        public Criteria andCostsTypeIsNotNull() {
            addCriterion("costs_type is not null");
            return (Criteria) this;
        }

        public Criteria andCostsTypeEqualTo(String value) {
            addCriterion("costs_type =", value, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeNotEqualTo(String value) {
            addCriterion("costs_type <>", value, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeGreaterThan(String value) {
            addCriterion("costs_type >", value, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("costs_type >=", value, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeLessThan(String value) {
            addCriterion("costs_type <", value, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeLessThanOrEqualTo(String value) {
            addCriterion("costs_type <=", value, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeLike(String value) {
            addCriterion("costs_type like", value, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeNotLike(String value) {
            addCriterion("costs_type not like", value, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeIn(List<String> values) {
            addCriterion("costs_type in", values, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeNotIn(List<String> values) {
            addCriterion("costs_type not in", values, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeBetween(String value1, String value2) {
            addCriterion("costs_type between", value1, value2, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTypeNotBetween(String value1, String value2) {
            addCriterion("costs_type not between", value1, value2, "costsType");
            return (Criteria) this;
        }

        public Criteria andCostsTargetIsNull() {
            addCriterion("costs_target is null");
            return (Criteria) this;
        }

        public Criteria andCostsTargetIsNotNull() {
            addCriterion("costs_target is not null");
            return (Criteria) this;
        }

        public Criteria andCostsTargetEqualTo(String value) {
            addCriterion("costs_target =", value, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetNotEqualTo(String value) {
            addCriterion("costs_target <>", value, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetGreaterThan(String value) {
            addCriterion("costs_target >", value, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetGreaterThanOrEqualTo(String value) {
            addCriterion("costs_target >=", value, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetLessThan(String value) {
            addCriterion("costs_target <", value, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetLessThanOrEqualTo(String value) {
            addCriterion("costs_target <=", value, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetLike(String value) {
            addCriterion("costs_target like", value, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetNotLike(String value) {
            addCriterion("costs_target not like", value, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetIn(List<String> values) {
            addCriterion("costs_target in", values, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetNotIn(List<String> values) {
            addCriterion("costs_target not in", values, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetBetween(String value1, String value2) {
            addCriterion("costs_target between", value1, value2, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsTargetNotBetween(String value1, String value2) {
            addCriterion("costs_target not between", value1, value2, "costsTarget");
            return (Criteria) this;
        }

        public Criteria andCostsDateIsNull() {
            addCriterion("costs_date is null");
            return (Criteria) this;
        }

        public Criteria andCostsDateIsNotNull() {
            addCriterion("costs_date is not null");
            return (Criteria) this;
        }

        public Criteria andCostsDateEqualTo(String value) {
            addCriterion("costs_date =", value, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateNotEqualTo(String value) {
            addCriterion("costs_date <>", value, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateGreaterThan(String value) {
            addCriterion("costs_date >", value, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateGreaterThanOrEqualTo(String value) {
            addCriterion("costs_date >=", value, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateLessThan(String value) {
            addCriterion("costs_date <", value, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateLessThanOrEqualTo(String value) {
            addCriterion("costs_date <=", value, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateLike(String value) {
            addCriterion("costs_date like", value, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateNotLike(String value) {
            addCriterion("costs_date not like", value, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateIn(List<String> values) {
            addCriterion("costs_date in", values, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateNotIn(List<String> values) {
            addCriterion("costs_date not in", values, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateBetween(String value1, String value2) {
            addCriterion("costs_date between", value1, value2, "costsDate");
            return (Criteria) this;
        }

        public Criteria andCostsDateNotBetween(String value1, String value2) {
            addCriterion("costs_date not between", value1, value2, "costsDate");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usercontroller_user_bill
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}