package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingItemPromotionalSaleSet;
import com.base.database.trading.model.TradingItemPromotionalSaleSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingItemPromotionalSaleSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    int countByExample(TradingItemPromotionalSaleSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    int deleteByExample(TradingItemPromotionalSaleSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    int insert(TradingItemPromotionalSaleSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    int insertSelective(TradingItemPromotionalSaleSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    List<TradingItemPromotionalSaleSet> selectByExample(TradingItemPromotionalSaleSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    TradingItemPromotionalSaleSet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingItemPromotionalSaleSet record, @Param("example") TradingItemPromotionalSaleSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingItemPromotionalSaleSet record, @Param("example") TradingItemPromotionalSaleSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingItemPromotionalSaleSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingItemPromotionalSaleSet record);
}