package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingItemPromotionalSaleRule;
import com.base.database.trading.model.TradingItemPromotionalSaleRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingItemPromotionalSaleRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    int countByExample(TradingItemPromotionalSaleRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    int deleteByExample(TradingItemPromotionalSaleRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    int insert(TradingItemPromotionalSaleRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    int insertSelective(TradingItemPromotionalSaleRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    List<TradingItemPromotionalSaleRule> selectByExample(TradingItemPromotionalSaleRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    TradingItemPromotionalSaleRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingItemPromotionalSaleRule record, @Param("example") TradingItemPromotionalSaleRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingItemPromotionalSaleRule record, @Param("example") TradingItemPromotionalSaleRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingItemPromotionalSaleRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item_promotionalsale_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingItemPromotionalSaleRule record);
}