package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingVeriftListingTask;
import com.base.database.trading.model.TradingVeriftListingTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingVeriftListingTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    int countByExample(TradingVeriftListingTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    int deleteByExample(TradingVeriftListingTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    int insert(TradingVeriftListingTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    int insertSelective(TradingVeriftListingTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    List<TradingVeriftListingTask> selectByExample(TradingVeriftListingTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    TradingVeriftListingTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingVeriftListingTask record, @Param("example") TradingVeriftListingTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingVeriftListingTask record, @Param("example") TradingVeriftListingTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingVeriftListingTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_verift_listing_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingVeriftListingTask record);
}