package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingStoreCategory;
import com.base.database.trading.model.TradingStoreCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingStoreCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    int countByExample(TradingStoreCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    int deleteByExample(TradingStoreCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    int insert(TradingStoreCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    int insertSelective(TradingStoreCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    List<TradingStoreCategory> selectByExample(TradingStoreCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    TradingStoreCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingStoreCategory record, @Param("example") TradingStoreCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingStoreCategory record, @Param("example") TradingStoreCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingStoreCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_store_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingStoreCategory record);
}