package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingCategoryTask;
import com.base.database.trading.model.TradingCategoryTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingCategoryTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    int countByExample(TradingCategoryTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    int deleteByExample(TradingCategoryTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    int insert(TradingCategoryTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    int insertSelective(TradingCategoryTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    List<TradingCategoryTask> selectByExample(TradingCategoryTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    TradingCategoryTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingCategoryTask record, @Param("example") TradingCategoryTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingCategoryTask record, @Param("example") TradingCategoryTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingCategoryTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_category_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingCategoryTask record);
}