package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingListingSet;
import com.base.database.trading.model.TradingListingSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingListingSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    int countByExample(TradingListingSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    int deleteByExample(TradingListingSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    int insert(TradingListingSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    int insertSelective(TradingListingSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    List<TradingListingSet> selectByExample(TradingListingSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    TradingListingSet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingListingSet record, @Param("example") TradingListingSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingListingSet record, @Param("example") TradingListingSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingListingSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingListingSet record);
}