package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingTembinListingLog;
import com.base.database.trading.model.TradingTembinListingLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingTembinListingLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    int countByExample(TradingTembinListingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    int deleteByExample(TradingTembinListingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    int insert(TradingTembinListingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    int insertSelective(TradingTembinListingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    List<TradingTembinListingLog> selectByExample(TradingTembinListingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    TradingTembinListingLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingTembinListingLog record, @Param("example") TradingTembinListingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingTembinListingLog record, @Param("example") TradingTembinListingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingTembinListingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_tembin_listing_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingTembinListingLog record);
}