package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingPicFile;
import com.base.database.trading.model.TradingPicFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingPicFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    int countByExample(TradingPicFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    int deleteByExample(TradingPicFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    int insert(TradingPicFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    int insertSelective(TradingPicFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    List<TradingPicFile> selectByExample(TradingPicFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    TradingPicFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingPicFile record, @Param("example") TradingPicFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingPicFile record, @Param("example") TradingPicFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingPicFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_pic_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingPicFile record);
}