package com.base.database.trading.mapper;

import com.base.database.trading.model.UsercontrollerEbayAccountInfo;
import com.base.database.trading.model.UsercontrollerEbayAccountInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsercontrollerEbayAccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    int countByExample(UsercontrollerEbayAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    int deleteByExample(UsercontrollerEbayAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    int insert(UsercontrollerEbayAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    int insertSelective(UsercontrollerEbayAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    List<UsercontrollerEbayAccountInfo> selectByExample(UsercontrollerEbayAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    UsercontrollerEbayAccountInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsercontrollerEbayAccountInfo record, @Param("example") UsercontrollerEbayAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsercontrollerEbayAccountInfo record, @Param("example") UsercontrollerEbayAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsercontrollerEbayAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_ebay_account_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsercontrollerEbayAccountInfo record);
}