package com.alibabasmt.database.smtproduct.model;

import java.util.Date;

public class SmtAeopSkuProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_aeopskuproperty.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_aeopskuproperty.skuPropertyId
     *
     * @mbggenerated
     */
    private Long skupropertyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_aeopskuproperty.propertyValueId
     *
     * @mbggenerated
     */
    private Long propertyvalueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_aeopskuproperty.propertyValueDefinitionName
     *
     * @mbggenerated
     */
    private String propertyvaluedefinitionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_aeopskuproperty.skuImage
     *
     * @mbggenerated
     */
    private String skuimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_aeopskuproperty.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_aeopskuproperty.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_aeopskuproperty.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_aeopskuproperty.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_aeopskuproperty.id
     *
     * @return the value of smt_aeopskuproperty.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_aeopskuproperty.id
     *
     * @param id the value for smt_aeopskuproperty.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_aeopskuproperty.skuPropertyId
     *
     * @return the value of smt_aeopskuproperty.skuPropertyId
     *
     * @mbggenerated
     */
    public Long getSkupropertyid() {
        return skupropertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_aeopskuproperty.skuPropertyId
     *
     * @param skupropertyid the value for smt_aeopskuproperty.skuPropertyId
     *
     * @mbggenerated
     */
    public void setSkupropertyid(Long skupropertyid) {
        this.skupropertyid = skupropertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_aeopskuproperty.propertyValueId
     *
     * @return the value of smt_aeopskuproperty.propertyValueId
     *
     * @mbggenerated
     */
    public Long getPropertyvalueid() {
        return propertyvalueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_aeopskuproperty.propertyValueId
     *
     * @param propertyvalueid the value for smt_aeopskuproperty.propertyValueId
     *
     * @mbggenerated
     */
    public void setPropertyvalueid(Long propertyvalueid) {
        this.propertyvalueid = propertyvalueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_aeopskuproperty.propertyValueDefinitionName
     *
     * @return the value of smt_aeopskuproperty.propertyValueDefinitionName
     *
     * @mbggenerated
     */
    public String getPropertyvaluedefinitionname() {
        return propertyvaluedefinitionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_aeopskuproperty.propertyValueDefinitionName
     *
     * @param propertyvaluedefinitionname the value for smt_aeopskuproperty.propertyValueDefinitionName
     *
     * @mbggenerated
     */
    public void setPropertyvaluedefinitionname(String propertyvaluedefinitionname) {
        this.propertyvaluedefinitionname = propertyvaluedefinitionname == null ? null : propertyvaluedefinitionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_aeopskuproperty.skuImage
     *
     * @return the value of smt_aeopskuproperty.skuImage
     *
     * @mbggenerated
     */
    public String getSkuimage() {
        return skuimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_aeopskuproperty.skuImage
     *
     * @param skuimage the value for smt_aeopskuproperty.skuImage
     *
     * @mbggenerated
     */
    public void setSkuimage(String skuimage) {
        this.skuimage = skuimage == null ? null : skuimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_aeopskuproperty.parent_id
     *
     * @return the value of smt_aeopskuproperty.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_aeopskuproperty.parent_id
     *
     * @param parentId the value for smt_aeopskuproperty.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_aeopskuproperty.create_time
     *
     * @return the value of smt_aeopskuproperty.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_aeopskuproperty.create_time
     *
     * @param createTime the value for smt_aeopskuproperty.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_aeopskuproperty.create_user
     *
     * @return the value of smt_aeopskuproperty.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_aeopskuproperty.create_user
     *
     * @param createUser the value for smt_aeopskuproperty.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_aeopskuproperty.update_time
     *
     * @return the value of smt_aeopskuproperty.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_aeopskuproperty.update_time
     *
     * @param updateTime the value for smt_aeopskuproperty.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}