package com.alibabasmt.database.smtproduct.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SmtAeopSkuPropertyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public SmtAeopSkuPropertyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidIsNull() {
            addCriterion("skuPropertyId is null");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidIsNotNull() {
            addCriterion("skuPropertyId is not null");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidEqualTo(Long value) {
            addCriterion("skuPropertyId =", value, "skupropertyid");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidNotEqualTo(Long value) {
            addCriterion("skuPropertyId <>", value, "skupropertyid");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidGreaterThan(Long value) {
            addCriterion("skuPropertyId >", value, "skupropertyid");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidGreaterThanOrEqualTo(Long value) {
            addCriterion("skuPropertyId >=", value, "skupropertyid");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidLessThan(Long value) {
            addCriterion("skuPropertyId <", value, "skupropertyid");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidLessThanOrEqualTo(Long value) {
            addCriterion("skuPropertyId <=", value, "skupropertyid");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidIn(List<Long> values) {
            addCriterion("skuPropertyId in", values, "skupropertyid");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidNotIn(List<Long> values) {
            addCriterion("skuPropertyId not in", values, "skupropertyid");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidBetween(Long value1, Long value2) {
            addCriterion("skuPropertyId between", value1, value2, "skupropertyid");
            return (Criteria) this;
        }

        public Criteria andSkupropertyidNotBetween(Long value1, Long value2) {
            addCriterion("skuPropertyId not between", value1, value2, "skupropertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidIsNull() {
            addCriterion("propertyValueId is null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidIsNotNull() {
            addCriterion("propertyValueId is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidEqualTo(Long value) {
            addCriterion("propertyValueId =", value, "propertyvalueid");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidNotEqualTo(Long value) {
            addCriterion("propertyValueId <>", value, "propertyvalueid");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidGreaterThan(Long value) {
            addCriterion("propertyValueId >", value, "propertyvalueid");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidGreaterThanOrEqualTo(Long value) {
            addCriterion("propertyValueId >=", value, "propertyvalueid");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidLessThan(Long value) {
            addCriterion("propertyValueId <", value, "propertyvalueid");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidLessThanOrEqualTo(Long value) {
            addCriterion("propertyValueId <=", value, "propertyvalueid");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidIn(List<Long> values) {
            addCriterion("propertyValueId in", values, "propertyvalueid");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidNotIn(List<Long> values) {
            addCriterion("propertyValueId not in", values, "propertyvalueid");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidBetween(Long value1, Long value2) {
            addCriterion("propertyValueId between", value1, value2, "propertyvalueid");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueidNotBetween(Long value1, Long value2) {
            addCriterion("propertyValueId not between", value1, value2, "propertyvalueid");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameIsNull() {
            addCriterion("propertyValueDefinitionName is null");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameIsNotNull() {
            addCriterion("propertyValueDefinitionName is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameEqualTo(String value) {
            addCriterion("propertyValueDefinitionName =", value, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameNotEqualTo(String value) {
            addCriterion("propertyValueDefinitionName <>", value, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameGreaterThan(String value) {
            addCriterion("propertyValueDefinitionName >", value, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameGreaterThanOrEqualTo(String value) {
            addCriterion("propertyValueDefinitionName >=", value, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameLessThan(String value) {
            addCriterion("propertyValueDefinitionName <", value, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameLessThanOrEqualTo(String value) {
            addCriterion("propertyValueDefinitionName <=", value, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameLike(String value) {
            addCriterion("propertyValueDefinitionName like", value, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameNotLike(String value) {
            addCriterion("propertyValueDefinitionName not like", value, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameIn(List<String> values) {
            addCriterion("propertyValueDefinitionName in", values, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameNotIn(List<String> values) {
            addCriterion("propertyValueDefinitionName not in", values, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameBetween(String value1, String value2) {
            addCriterion("propertyValueDefinitionName between", value1, value2, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluedefinitionnameNotBetween(String value1, String value2) {
            addCriterion("propertyValueDefinitionName not between", value1, value2, "propertyvaluedefinitionname");
            return (Criteria) this;
        }

        public Criteria andSkuimageIsNull() {
            addCriterion("skuImage is null");
            return (Criteria) this;
        }

        public Criteria andSkuimageIsNotNull() {
            addCriterion("skuImage is not null");
            return (Criteria) this;
        }

        public Criteria andSkuimageEqualTo(String value) {
            addCriterion("skuImage =", value, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageNotEqualTo(String value) {
            addCriterion("skuImage <>", value, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageGreaterThan(String value) {
            addCriterion("skuImage >", value, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageGreaterThanOrEqualTo(String value) {
            addCriterion("skuImage >=", value, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageLessThan(String value) {
            addCriterion("skuImage <", value, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageLessThanOrEqualTo(String value) {
            addCriterion("skuImage <=", value, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageLike(String value) {
            addCriterion("skuImage like", value, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageNotLike(String value) {
            addCriterion("skuImage not like", value, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageIn(List<String> values) {
            addCriterion("skuImage in", values, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageNotIn(List<String> values) {
            addCriterion("skuImage not in", values, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageBetween(String value1, String value2) {
            addCriterion("skuImage between", value1, value2, "skuimage");
            return (Criteria) this;
        }

        public Criteria andSkuimageNotBetween(String value1, String value2) {
            addCriterion("skuImage not between", value1, value2, "skuimage");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Long value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Long value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Long value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Long value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Long value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Long> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Long> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Long value1, Long value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Long value1, Long value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Long value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Long value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Long value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Long value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Long value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Long value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Long> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Long> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Long value1, Long value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Long value1, Long value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}