package com.alibabasmt.database.smtproduct.model;

import java.util.Date;

public class SmtProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.deliveryTime
     *
     * @mbggenerated
     */
    private Integer deliverytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.promiseTemplateId
     *
     * @mbggenerated
     */
    private Long promisetemplateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.categoryId
     *
     * @mbggenerated
     */
    private Long categoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.subject
     *
     * @mbggenerated
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.keyword
     *
     * @mbggenerated
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.productMoreKeywords1
     *
     * @mbggenerated
     */
    private String productmorekeywords1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.productMoreKeywords2
     *
     * @mbggenerated
     */
    private String productmorekeywords2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.alie_groupId
     *
     * @mbggenerated
     */
    private Integer alieGroupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.productPrice
     *
     * @mbggenerated
     */
    private Double productprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.freightTemplateId
     *
     * @mbggenerated
     */
    private Long freighttemplateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.isImageDynamic
     *
     * @mbggenerated
     */
    private String isimagedynamic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.isImageWatermark
     *
     * @mbggenerated
     */
    private String isimagewatermark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.imageURLs
     *
     * @mbggenerated
     */
    private String imageurls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.productUnit
     *
     * @mbggenerated
     */
    private Long productunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.packageType
     *
     * @mbggenerated
     */
    private String packagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.lotNum
     *
     * @mbggenerated
     */
    private Integer lotnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.packageLength
     *
     * @mbggenerated
     */
    private Integer packagelength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.packageWidth
     *
     * @mbggenerated
     */
    private Integer packagewidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.packageHeight
     *
     * @mbggenerated
     */
    private Integer packageheight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.grossWeight
     *
     * @mbggenerated
     */
    private Double grossweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.isPackSell
     *
     * @mbggenerated
     */
    private String ispacksell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.baseUnit
     *
     * @mbggenerated
     */
    private Integer baseunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.addUnit
     *
     * @mbggenerated
     */
    private Integer addunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.addWeight
     *
     * @mbggenerated
     */
    private Double addweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.wsValidNum
     *
     * @mbggenerated
     */
    private Integer wsvalidnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.alie_src
     *
     * @mbggenerated
     */
    private String alieSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.bulkOrder
     *
     * @mbggenerated
     */
    private Integer bulkorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.bulkDiscount
     *
     * @mbggenerated
     */
    private Integer bulkdiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.sizechartId
     *
     * @mbggenerated
     */
    private Long sizechartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.productId
     *
     * @mbggenerated
     */
    private Long productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.wsOfflineDate
     *
     * @mbggenerated
     */
    private String wsofflinedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.wsDisplay
     *
     * @mbggenerated
     */
    private String wsdisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.ownerMemberSeq
     *
     * @mbggenerated
     */
    private Long ownermemberseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.productStatusType
     *
     * @mbggenerated
     */
    private String productstatustype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.create_org_id
     *
     * @mbggenerated
     */
    private Long createOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.ownerMemberId
     *
     * @mbggenerated
     */
    private String ownermemberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smt_product.alie_detail
     *
     * @mbggenerated
     */
    private String alieDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.id
     *
     * @return the value of smt_product.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.id
     *
     * @param id the value for smt_product.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.deliveryTime
     *
     * @return the value of smt_product.deliveryTime
     *
     * @mbggenerated
     */
    public Integer getDeliverytime() {
        return deliverytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.deliveryTime
     *
     * @param deliverytime the value for smt_product.deliveryTime
     *
     * @mbggenerated
     */
    public void setDeliverytime(Integer deliverytime) {
        this.deliverytime = deliverytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.promiseTemplateId
     *
     * @return the value of smt_product.promiseTemplateId
     *
     * @mbggenerated
     */
    public Long getPromisetemplateid() {
        return promisetemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.promiseTemplateId
     *
     * @param promisetemplateid the value for smt_product.promiseTemplateId
     *
     * @mbggenerated
     */
    public void setPromisetemplateid(Long promisetemplateid) {
        this.promisetemplateid = promisetemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.categoryId
     *
     * @return the value of smt_product.categoryId
     *
     * @mbggenerated
     */
    public Long getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.categoryId
     *
     * @param categoryid the value for smt_product.categoryId
     *
     * @mbggenerated
     */
    public void setCategoryid(Long categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.subject
     *
     * @return the value of smt_product.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.subject
     *
     * @param subject the value for smt_product.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.keyword
     *
     * @return the value of smt_product.keyword
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.keyword
     *
     * @param keyword the value for smt_product.keyword
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.productMoreKeywords1
     *
     * @return the value of smt_product.productMoreKeywords1
     *
     * @mbggenerated
     */
    public String getProductmorekeywords1() {
        return productmorekeywords1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.productMoreKeywords1
     *
     * @param productmorekeywords1 the value for smt_product.productMoreKeywords1
     *
     * @mbggenerated
     */
    public void setProductmorekeywords1(String productmorekeywords1) {
        this.productmorekeywords1 = productmorekeywords1 == null ? null : productmorekeywords1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.productMoreKeywords2
     *
     * @return the value of smt_product.productMoreKeywords2
     *
     * @mbggenerated
     */
    public String getProductmorekeywords2() {
        return productmorekeywords2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.productMoreKeywords2
     *
     * @param productmorekeywords2 the value for smt_product.productMoreKeywords2
     *
     * @mbggenerated
     */
    public void setProductmorekeywords2(String productmorekeywords2) {
        this.productmorekeywords2 = productmorekeywords2 == null ? null : productmorekeywords2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.alie_groupId
     *
     * @return the value of smt_product.alie_groupId
     *
     * @mbggenerated
     */
    public Integer getAlieGroupid() {
        return alieGroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.alie_groupId
     *
     * @param alieGroupid the value for smt_product.alie_groupId
     *
     * @mbggenerated
     */
    public void setAlieGroupid(Integer alieGroupid) {
        this.alieGroupid = alieGroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.productPrice
     *
     * @return the value of smt_product.productPrice
     *
     * @mbggenerated
     */
    public Double getProductprice() {
        return productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.productPrice
     *
     * @param productprice the value for smt_product.productPrice
     *
     * @mbggenerated
     */
    public void setProductprice(Double productprice) {
        this.productprice = productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.freightTemplateId
     *
     * @return the value of smt_product.freightTemplateId
     *
     * @mbggenerated
     */
    public Long getFreighttemplateid() {
        return freighttemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.freightTemplateId
     *
     * @param freighttemplateid the value for smt_product.freightTemplateId
     *
     * @mbggenerated
     */
    public void setFreighttemplateid(Long freighttemplateid) {
        this.freighttemplateid = freighttemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.isImageDynamic
     *
     * @return the value of smt_product.isImageDynamic
     *
     * @mbggenerated
     */
    public String getIsimagedynamic() {
        return isimagedynamic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.isImageDynamic
     *
     * @param isimagedynamic the value for smt_product.isImageDynamic
     *
     * @mbggenerated
     */
    public void setIsimagedynamic(String isimagedynamic) {
        this.isimagedynamic = isimagedynamic == null ? null : isimagedynamic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.isImageWatermark
     *
     * @return the value of smt_product.isImageWatermark
     *
     * @mbggenerated
     */
    public String getIsimagewatermark() {
        return isimagewatermark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.isImageWatermark
     *
     * @param isimagewatermark the value for smt_product.isImageWatermark
     *
     * @mbggenerated
     */
    public void setIsimagewatermark(String isimagewatermark) {
        this.isimagewatermark = isimagewatermark == null ? null : isimagewatermark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.imageURLs
     *
     * @return the value of smt_product.imageURLs
     *
     * @mbggenerated
     */
    public String getImageurls() {
        return imageurls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.imageURLs
     *
     * @param imageurls the value for smt_product.imageURLs
     *
     * @mbggenerated
     */
    public void setImageurls(String imageurls) {
        this.imageurls = imageurls == null ? null : imageurls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.productUnit
     *
     * @return the value of smt_product.productUnit
     *
     * @mbggenerated
     */
    public Long getProductunit() {
        return productunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.productUnit
     *
     * @param productunit the value for smt_product.productUnit
     *
     * @mbggenerated
     */
    public void setProductunit(Long productunit) {
        this.productunit = productunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.packageType
     *
     * @return the value of smt_product.packageType
     *
     * @mbggenerated
     */
    public String getPackagetype() {
        return packagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.packageType
     *
     * @param packagetype the value for smt_product.packageType
     *
     * @mbggenerated
     */
    public void setPackagetype(String packagetype) {
        this.packagetype = packagetype == null ? null : packagetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.lotNum
     *
     * @return the value of smt_product.lotNum
     *
     * @mbggenerated
     */
    public Integer getLotnum() {
        return lotnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.lotNum
     *
     * @param lotnum the value for smt_product.lotNum
     *
     * @mbggenerated
     */
    public void setLotnum(Integer lotnum) {
        this.lotnum = lotnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.packageLength
     *
     * @return the value of smt_product.packageLength
     *
     * @mbggenerated
     */
    public Integer getPackagelength() {
        return packagelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.packageLength
     *
     * @param packagelength the value for smt_product.packageLength
     *
     * @mbggenerated
     */
    public void setPackagelength(Integer packagelength) {
        this.packagelength = packagelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.packageWidth
     *
     * @return the value of smt_product.packageWidth
     *
     * @mbggenerated
     */
    public Integer getPackagewidth() {
        return packagewidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.packageWidth
     *
     * @param packagewidth the value for smt_product.packageWidth
     *
     * @mbggenerated
     */
    public void setPackagewidth(Integer packagewidth) {
        this.packagewidth = packagewidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.packageHeight
     *
     * @return the value of smt_product.packageHeight
     *
     * @mbggenerated
     */
    public Integer getPackageheight() {
        return packageheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.packageHeight
     *
     * @param packageheight the value for smt_product.packageHeight
     *
     * @mbggenerated
     */
    public void setPackageheight(Integer packageheight) {
        this.packageheight = packageheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.grossWeight
     *
     * @return the value of smt_product.grossWeight
     *
     * @mbggenerated
     */
    public Double getGrossweight() {
        return grossweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.grossWeight
     *
     * @param grossweight the value for smt_product.grossWeight
     *
     * @mbggenerated
     */
    public void setGrossweight(Double grossweight) {
        this.grossweight = grossweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.isPackSell
     *
     * @return the value of smt_product.isPackSell
     *
     * @mbggenerated
     */
    public String getIspacksell() {
        return ispacksell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.isPackSell
     *
     * @param ispacksell the value for smt_product.isPackSell
     *
     * @mbggenerated
     */
    public void setIspacksell(String ispacksell) {
        this.ispacksell = ispacksell == null ? null : ispacksell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.baseUnit
     *
     * @return the value of smt_product.baseUnit
     *
     * @mbggenerated
     */
    public Integer getBaseunit() {
        return baseunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.baseUnit
     *
     * @param baseunit the value for smt_product.baseUnit
     *
     * @mbggenerated
     */
    public void setBaseunit(Integer baseunit) {
        this.baseunit = baseunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.addUnit
     *
     * @return the value of smt_product.addUnit
     *
     * @mbggenerated
     */
    public Integer getAddunit() {
        return addunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.addUnit
     *
     * @param addunit the value for smt_product.addUnit
     *
     * @mbggenerated
     */
    public void setAddunit(Integer addunit) {
        this.addunit = addunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.addWeight
     *
     * @return the value of smt_product.addWeight
     *
     * @mbggenerated
     */
    public Double getAddweight() {
        return addweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.addWeight
     *
     * @param addweight the value for smt_product.addWeight
     *
     * @mbggenerated
     */
    public void setAddweight(Double addweight) {
        this.addweight = addweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.wsValidNum
     *
     * @return the value of smt_product.wsValidNum
     *
     * @mbggenerated
     */
    public Integer getWsvalidnum() {
        return wsvalidnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.wsValidNum
     *
     * @param wsvalidnum the value for smt_product.wsValidNum
     *
     * @mbggenerated
     */
    public void setWsvalidnum(Integer wsvalidnum) {
        this.wsvalidnum = wsvalidnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.alie_src
     *
     * @return the value of smt_product.alie_src
     *
     * @mbggenerated
     */
    public String getAlieSrc() {
        return alieSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.alie_src
     *
     * @param alieSrc the value for smt_product.alie_src
     *
     * @mbggenerated
     */
    public void setAlieSrc(String alieSrc) {
        this.alieSrc = alieSrc == null ? null : alieSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.bulkOrder
     *
     * @return the value of smt_product.bulkOrder
     *
     * @mbggenerated
     */
    public Integer getBulkorder() {
        return bulkorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.bulkOrder
     *
     * @param bulkorder the value for smt_product.bulkOrder
     *
     * @mbggenerated
     */
    public void setBulkorder(Integer bulkorder) {
        this.bulkorder = bulkorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.bulkDiscount
     *
     * @return the value of smt_product.bulkDiscount
     *
     * @mbggenerated
     */
    public Integer getBulkdiscount() {
        return bulkdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.bulkDiscount
     *
     * @param bulkdiscount the value for smt_product.bulkDiscount
     *
     * @mbggenerated
     */
    public void setBulkdiscount(Integer bulkdiscount) {
        this.bulkdiscount = bulkdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.sizechartId
     *
     * @return the value of smt_product.sizechartId
     *
     * @mbggenerated
     */
    public Long getSizechartid() {
        return sizechartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.sizechartId
     *
     * @param sizechartid the value for smt_product.sizechartId
     *
     * @mbggenerated
     */
    public void setSizechartid(Long sizechartid) {
        this.sizechartid = sizechartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.productId
     *
     * @return the value of smt_product.productId
     *
     * @mbggenerated
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.productId
     *
     * @param productid the value for smt_product.productId
     *
     * @mbggenerated
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.summary
     *
     * @return the value of smt_product.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.summary
     *
     * @param summary the value for smt_product.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.wsOfflineDate
     *
     * @return the value of smt_product.wsOfflineDate
     *
     * @mbggenerated
     */
    public String getWsofflinedate() {
        return wsofflinedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.wsOfflineDate
     *
     * @param wsofflinedate the value for smt_product.wsOfflineDate
     *
     * @mbggenerated
     */
    public void setWsofflinedate(String wsofflinedate) {
        this.wsofflinedate = wsofflinedate == null ? null : wsofflinedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.wsDisplay
     *
     * @return the value of smt_product.wsDisplay
     *
     * @mbggenerated
     */
    public String getWsdisplay() {
        return wsdisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.wsDisplay
     *
     * @param wsdisplay the value for smt_product.wsDisplay
     *
     * @mbggenerated
     */
    public void setWsdisplay(String wsdisplay) {
        this.wsdisplay = wsdisplay == null ? null : wsdisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.ownerMemberSeq
     *
     * @return the value of smt_product.ownerMemberSeq
     *
     * @mbggenerated
     */
    public Long getOwnermemberseq() {
        return ownermemberseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.ownerMemberSeq
     *
     * @param ownermemberseq the value for smt_product.ownerMemberSeq
     *
     * @mbggenerated
     */
    public void setOwnermemberseq(Long ownermemberseq) {
        this.ownermemberseq = ownermemberseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.productStatusType
     *
     * @return the value of smt_product.productStatusType
     *
     * @mbggenerated
     */
    public String getProductstatustype() {
        return productstatustype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.productStatusType
     *
     * @param productstatustype the value for smt_product.productStatusType
     *
     * @mbggenerated
     */
    public void setProductstatustype(String productstatustype) {
        this.productstatustype = productstatustype == null ? null : productstatustype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.create_time
     *
     * @return the value of smt_product.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.create_time
     *
     * @param createTime the value for smt_product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.create_user
     *
     * @return the value of smt_product.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.create_user
     *
     * @param createUser the value for smt_product.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.create_org_id
     *
     * @return the value of smt_product.create_org_id
     *
     * @mbggenerated
     */
    public Long getCreateOrgId() {
        return createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.create_org_id
     *
     * @param createOrgId the value for smt_product.create_org_id
     *
     * @mbggenerated
     */
    public void setCreateOrgId(Long createOrgId) {
        this.createOrgId = createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.update_time
     *
     * @return the value of smt_product.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.update_time
     *
     * @param updateTime the value for smt_product.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.ownerMemberId
     *
     * @return the value of smt_product.ownerMemberId
     *
     * @mbggenerated
     */
    public String getOwnermemberid() {
        return ownermemberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.ownerMemberId
     *
     * @param ownermemberid the value for smt_product.ownerMemberId
     *
     * @mbggenerated
     */
    public void setOwnermemberid(String ownermemberid) {
        this.ownermemberid = ownermemberid == null ? null : ownermemberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smt_product.alie_detail
     *
     * @return the value of smt_product.alie_detail
     *
     * @mbggenerated
     */
    public String getAlieDetail() {
        return alieDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smt_product.alie_detail
     *
     * @param alieDetail the value for smt_product.alie_detail
     *
     * @mbggenerated
     */
    public void setAlieDetail(String alieDetail) {
        this.alieDetail = alieDetail == null ? null : alieDetail.trim();
    }
}