package com.alibabasmt.database.smtorder.mapper;

import com.alibabasmt.database.smtorder.model.SmtOrderDetails;
import com.alibabasmt.database.smtorder.model.SmtOrderDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtOrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    int countByExample(SmtOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    int deleteByExample(SmtOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    int insert(SmtOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    int insertSelective(SmtOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    List<SmtOrderDetails> selectByExample(SmtOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    SmtOrderDetails selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtOrderDetails record, @Param("example") SmtOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtOrderDetails record, @Param("example") SmtOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtOrderDetails record);
}