package com.alibabasmt.database.smtorder.mapper;

import com.alibabasmt.database.smtorder.model.SmtOrderTable;
import com.alibabasmt.database.smtorder.model.SmtOrderTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtOrderTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    int countByExample(SmtOrderTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    int deleteByExample(SmtOrderTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    int insert(SmtOrderTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    int insertSelective(SmtOrderTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    List<SmtOrderTable> selectByExample(SmtOrderTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    SmtOrderTable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtOrderTable record, @Param("example") SmtOrderTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtOrderTable record, @Param("example") SmtOrderTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtOrderTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtOrderTable record);
}