package com.alibabasmt.database.smtorder.mapper;

import com.alibabasmt.database.smtorder.model.SmtOrderMessage;
import com.alibabasmt.database.smtorder.model.SmtOrderMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtOrderMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int countByExample(SmtOrderMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int deleteByExample(SmtOrderMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int insert(SmtOrderMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int insertSelective(SmtOrderMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    List<SmtOrderMessage> selectByExampleWithBLOBs(SmtOrderMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    List<SmtOrderMessage> selectByExample(SmtOrderMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    SmtOrderMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtOrderMessage record, @Param("example") SmtOrderMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SmtOrderMessage record, @Param("example") SmtOrderMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtOrderMessage record, @Param("example") SmtOrderMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtOrderMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SmtOrderMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtOrderMessage record);
}