package com.alibabasmt.database.smtorder.mapper;

import com.alibabasmt.database.smtorder.model.SmtOrderBuyerInfo;
import com.alibabasmt.database.smtorder.model.SmtOrderBuyerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtOrderBuyerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    int countByExample(SmtOrderBuyerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    int deleteByExample(SmtOrderBuyerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    int insert(SmtOrderBuyerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    int insertSelective(SmtOrderBuyerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    List<SmtOrderBuyerInfo> selectByExample(SmtOrderBuyerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    SmtOrderBuyerInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtOrderBuyerInfo record, @Param("example") SmtOrderBuyerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtOrderBuyerInfo record, @Param("example") SmtOrderBuyerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtOrderBuyerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_buyer_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtOrderBuyerInfo record);
}