package com.alibabasmt.database.smtorder.mapper;

import com.alibabasmt.database.smtorder.model.SmtOrderLog;
import com.alibabasmt.database.smtorder.model.SmtOrderLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtOrderLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    int countByExample(SmtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    int deleteByExample(SmtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    int insert(SmtOrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    int insertSelective(SmtOrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    List<SmtOrderLog> selectByExample(SmtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    SmtOrderLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtOrderLog record, @Param("example") SmtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtOrderLog record, @Param("example") SmtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtOrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtOrderLog record);
}