package com.alibabasmt.database.smtorder.mapper;

import com.alibabasmt.database.smtorder.model.SmtOrderChildrenOrder;
import com.alibabasmt.database.smtorder.model.SmtOrderChildrenOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtOrderChildrenOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    int countByExample(SmtOrderChildrenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    int deleteByExample(SmtOrderChildrenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    int insert(SmtOrderChildrenOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    int insertSelective(SmtOrderChildrenOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    List<SmtOrderChildrenOrder> selectByExample(SmtOrderChildrenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    SmtOrderChildrenOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtOrderChildrenOrder record, @Param("example") SmtOrderChildrenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtOrderChildrenOrder record, @Param("example") SmtOrderChildrenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtOrderChildrenOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_children_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtOrderChildrenOrder record);
}