package com.alibabasmt.database.smtorder.mapper;

import com.alibabasmt.database.smtorder.model.SmtOrderProductAttributes;
import com.alibabasmt.database.smtorder.model.SmtOrderProductAttributesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtOrderProductAttributesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    int countByExample(SmtOrderProductAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    int deleteByExample(SmtOrderProductAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    int insert(SmtOrderProductAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    int insertSelective(SmtOrderProductAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    List<SmtOrderProductAttributes> selectByExample(SmtOrderProductAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    SmtOrderProductAttributes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtOrderProductAttributes record, @Param("example") SmtOrderProductAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtOrderProductAttributes record, @Param("example") SmtOrderProductAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtOrderProductAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_product_attributes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtOrderProductAttributes record);
}