package com.alibabasmt.database.smtorder.mapper;

import com.alibabasmt.database.smtorder.model.SmtOrderChildOrderDetails;
import com.alibabasmt.database.smtorder.model.SmtOrderChildOrderDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtOrderChildOrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    int countByExample(SmtOrderChildOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    int deleteByExample(SmtOrderChildOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    int insert(SmtOrderChildOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    int insertSelective(SmtOrderChildOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    List<SmtOrderChildOrderDetails> selectByExample(SmtOrderChildOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    SmtOrderChildOrderDetails selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtOrderChildOrderDetails record, @Param("example") SmtOrderChildOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtOrderChildOrderDetails record, @Param("example") SmtOrderChildOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtOrderChildOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtOrderChildOrderDetails record);
}