package com.alibabasmt.database.smtorder.mapper;

import com.alibabasmt.database.smtorder.model.SmtOrderChildOrderItemInfo;
import com.alibabasmt.database.smtorder.model.SmtOrderChildOrderItemInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtOrderChildOrderItemInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    int countByExample(SmtOrderChildOrderItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    int deleteByExample(SmtOrderChildOrderItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    int insert(SmtOrderChildOrderItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    int insertSelective(SmtOrderChildOrderItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    List<SmtOrderChildOrderItemInfo> selectByExample(SmtOrderChildOrderItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    SmtOrderChildOrderItemInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtOrderChildOrderItemInfo record, @Param("example") SmtOrderChildOrderItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtOrderChildOrderItemInfo record, @Param("example") SmtOrderChildOrderItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtOrderChildOrderItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_order_child_order_iteminfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtOrderChildOrderItemInfo record);
}