package com.alibabasmt.database.smttask.mapper;

import com.alibabasmt.database.smttask.model.TaskSmtOrder;
import com.alibabasmt.database.smttask.model.TaskSmtOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskSmtOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    int countByExample(TaskSmtOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    int deleteByExample(TaskSmtOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    int insert(TaskSmtOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    int insertSelective(TaskSmtOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    List<TaskSmtOrder> selectByExample(TaskSmtOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    TaskSmtOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TaskSmtOrder record, @Param("example") TaskSmtOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TaskSmtOrder record, @Param("example") TaskSmtOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskSmtOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_smt_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskSmtOrder record);
}