package com.base.database.trading.model;

import java.util.Date;

public class UsercontrollerEbayAccountInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercontroller_ebay_account_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercontroller_ebay_account_info.eBay_ID
     *
     * @mbggenerated
     */
    private Long ebayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercontroller_ebay_account_info.FeedbackScore
     *
     * @mbggenerated
     */
    private String feedbackscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercontroller_ebay_account_info.PositiveFeedbackPercent
     *
     * @mbggenerated
     */
    private String positivefeedbackpercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercontroller_ebay_account_info.Status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercontroller_ebay_account_info.UserIDLastChanged
     *
     * @mbggenerated
     */
    private String useridlastchanged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercontroller_ebay_account_info.update_Time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercontroller_ebay_account_info.id
     *
     * @return the value of usercontroller_ebay_account_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercontroller_ebay_account_info.id
     *
     * @param id the value for usercontroller_ebay_account_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercontroller_ebay_account_info.eBay_ID
     *
     * @return the value of usercontroller_ebay_account_info.eBay_ID
     *
     * @mbggenerated
     */
    public Long getEbayId() {
        return ebayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercontroller_ebay_account_info.eBay_ID
     *
     * @param ebayId the value for usercontroller_ebay_account_info.eBay_ID
     *
     * @mbggenerated
     */
    public void setEbayId(Long ebayId) {
        this.ebayId = ebayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercontroller_ebay_account_info.FeedbackScore
     *
     * @return the value of usercontroller_ebay_account_info.FeedbackScore
     *
     * @mbggenerated
     */
    public String getFeedbackscore() {
        return feedbackscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercontroller_ebay_account_info.FeedbackScore
     *
     * @param feedbackscore the value for usercontroller_ebay_account_info.FeedbackScore
     *
     * @mbggenerated
     */
    public void setFeedbackscore(String feedbackscore) {
        this.feedbackscore = feedbackscore == null ? null : feedbackscore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercontroller_ebay_account_info.PositiveFeedbackPercent
     *
     * @return the value of usercontroller_ebay_account_info.PositiveFeedbackPercent
     *
     * @mbggenerated
     */
    public String getPositivefeedbackpercent() {
        return positivefeedbackpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercontroller_ebay_account_info.PositiveFeedbackPercent
     *
     * @param positivefeedbackpercent the value for usercontroller_ebay_account_info.PositiveFeedbackPercent
     *
     * @mbggenerated
     */
    public void setPositivefeedbackpercent(String positivefeedbackpercent) {
        this.positivefeedbackpercent = positivefeedbackpercent == null ? null : positivefeedbackpercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercontroller_ebay_account_info.Status
     *
     * @return the value of usercontroller_ebay_account_info.Status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercontroller_ebay_account_info.Status
     *
     * @param status the value for usercontroller_ebay_account_info.Status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercontroller_ebay_account_info.UserIDLastChanged
     *
     * @return the value of usercontroller_ebay_account_info.UserIDLastChanged
     *
     * @mbggenerated
     */
    public String getUseridlastchanged() {
        return useridlastchanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercontroller_ebay_account_info.UserIDLastChanged
     *
     * @param useridlastchanged the value for usercontroller_ebay_account_info.UserIDLastChanged
     *
     * @mbggenerated
     */
    public void setUseridlastchanged(String useridlastchanged) {
        this.useridlastchanged = useridlastchanged == null ? null : useridlastchanged.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercontroller_ebay_account_info.update_Time
     *
     * @return the value of usercontroller_ebay_account_info.update_Time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercontroller_ebay_account_info.update_Time
     *
     * @param updateTime the value for usercontroller_ebay_account_info.update_Time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}