package com.alibabasmt.database.smtmessage.mapper;

import com.alibabasmt.database.smtmessage.model.SmtMessage;
import com.alibabasmt.database.smtmessage.model.SmtMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int countByExample(SmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int deleteByExample(SmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int insert(SmtMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int insertSelective(SmtMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    List<SmtMessage> selectByExampleWithBLOBs(SmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    List<SmtMessage> selectByExample(SmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    SmtMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtMessage record, @Param("example") SmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SmtMessage record, @Param("example") SmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtMessage record, @Param("example") SmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SmtMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtMessage record);
}