package com.alibabasmt.database.smtproduct.mapper;

import com.alibabasmt.database.smtproduct.model.SmtAeopaeProductSku;
import com.alibabasmt.database.smtproduct.model.SmtAeopaeProductSkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtAeopaeProductSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    int countByExample(SmtAeopaeProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    int deleteByExample(SmtAeopaeProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    int insert(SmtAeopaeProductSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    int insertSelective(SmtAeopaeProductSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    List<SmtAeopaeProductSku> selectByExample(SmtAeopaeProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    SmtAeopaeProductSku selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtAeopaeProductSku record, @Param("example") SmtAeopaeProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtAeopaeProductSku record, @Param("example") SmtAeopaeProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtAeopaeProductSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductsku
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtAeopaeProductSku record);
}