package com.alibabasmt.database.smtproduct.mapper;

import com.alibabasmt.database.smtproduct.model.SmtAeopaeProductProperty;
import com.alibabasmt.database.smtproduct.model.SmtAeopaeProductPropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtAeopaeProductPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    int countByExample(SmtAeopaeProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    int deleteByExample(SmtAeopaeProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    int insert(SmtAeopaeProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    int insertSelective(SmtAeopaeProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    List<SmtAeopaeProductProperty> selectByExample(SmtAeopaeProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    SmtAeopaeProductProperty selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtAeopaeProductProperty record, @Param("example") SmtAeopaeProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtAeopaeProductProperty record, @Param("example") SmtAeopaeProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtAeopaeProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopaeproductproperty
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtAeopaeProductProperty record);
}