package com.alibabasmt.database.smtproduct.mapper;

import com.alibabasmt.database.smtproduct.model.SmtAeopSkuProperty;
import com.alibabasmt.database.smtproduct.model.SmtAeopSkuPropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtAeopSkuPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    int countByExample(SmtAeopSkuPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    int deleteByExample(SmtAeopSkuPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    int insert(SmtAeopSkuProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    int insertSelective(SmtAeopSkuProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    List<SmtAeopSkuProperty> selectByExample(SmtAeopSkuPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    SmtAeopSkuProperty selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtAeopSkuProperty record, @Param("example") SmtAeopSkuPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtAeopSkuProperty record, @Param("example") SmtAeopSkuPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtAeopSkuProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_aeopskuproperty
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtAeopSkuProperty record);
}