package com.alibabasmt.database.smtproduct.mapper;

import com.alibabasmt.database.smtproduct.model.SmtProductListing;
import com.alibabasmt.database.smtproduct.model.SmtProductListingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmtProductListingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int countByExample(SmtProductListingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int deleteByExample(SmtProductListingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int insert(SmtProductListing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int insertSelective(SmtProductListing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    List<SmtProductListing> selectByExampleWithBLOBs(SmtProductListingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    List<SmtProductListing> selectByExample(SmtProductListingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    SmtProductListing selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmtProductListing record, @Param("example") SmtProductListingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SmtProductListing record, @Param("example") SmtProductListingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmtProductListing record, @Param("example") SmtProductListingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmtProductListing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SmtProductListing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smt_product_listing
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmtProductListing record);
}